POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "provider" : "Kakao",
    "token" : "avcd-dfafa-fgafafaa"
}


### 2
POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
"refreshToken" : "avcd-dfafa-fgafafaa"
}


### 3
GET http://localhost:5000/api/v1/dalbit/device/myDevices
Authorization: Bearer abdca=dadavsv-adasd
